# Generated by Django 2.0 on 2018-06-14 02:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('Do', 'Downloaded'), ('Up', 'Uploaded'), ('De', 'Deleted'), ('Sh', 'Shared'), ('Em', 'Emailed')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('saved_as', models.CharField(max_length=255)),
                ('size', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=500, null=True)),
                ('s3_bucket', models.CharField(default='central', max_length=255)),
                ('s3_bucket_key', models.CharField(max_length=255, unique=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailBucket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('download_url', models.URLField()),
                ('receiver', models.EmailField(editable=False, max_length=255)),
                ('bucket_exists', models.BooleanField(default=True)),
                ('downloaded', models.BooleanField(default=False)),
                ('downloaded_at', models.DateTimeField(null=True)),
                ('bucket', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='server.Bucket')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualEncryptionKeys',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encrypted_key', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShareBucket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('download_token', models.CharField(editable=False, max_length=255)),
                ('receiver', models.EmailField(editable=False, max_length=255)),
                ('bucket_exists', models.BooleanField(default=True)),
                ('encrypted', models.BooleanField(default=False)),
                ('downloaded', models.BooleanField(default=False)),
                ('downloaded_at', models.DateTimeField(null=True)),
                ('bucket', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='server.Bucket')),
            ],
        ),
        migrations.CreateModel(
            name='SharedEncryptionKeyModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encrypted_key', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('pub_key', models.TextField(max_length=1024, unique=True)),
                ('size_used', models.IntegerField(default=0)),
                ('size_limit', models.IntegerField(default=500000)),
                ('s3_bucket', models.CharField(default='central', max_length=255)),
                ('s3_bucket_key', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='sharedencryptionkeymodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='server.User'),
        ),
        migrations.AddField(
            model_name='sharedencryptionkeymodel',
            name='created_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='server.User'),
        ),
        migrations.AddField(
            model_name='sharebucket',
            name='encrypted_with',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.SharedEncryptionKeyModel'),
        ),
        migrations.AddField(
            model_name='sharebucket',
            name='sender',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='server.User'),
        ),
        migrations.AddField(
            model_name='individualencryptionkeys',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.User'),
        ),
        migrations.AddField(
            model_name='emailbucket',
            name='sender',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='server.User'),
        ),
        migrations.AddField(
            model_name='bucket',
            name='encrypted_with',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.IndividualEncryptionKeys'),
        ),
        migrations.AddField(
            model_name='bucket',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.User'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='bucket',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='server.Bucket'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='server.User'),
        ),
    ]
