# Generated by Django 2.0 on 2018-06-19 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('encrypted_bucket_encryption_key', models.TextField(max_length=2048, null=True)),
                ('encrypted_priv_key', models.TextField(max_length=4096, null=True, unique=True)),
                ('pub_key', models.TextField(max_length=4096, unique=True)),
                ('real_size_used', models.IntegerField(default=0)),
                ('virtual_size_used', models.IntegerField(default=0)),
                ('virtual_size_limit', models.IntegerField(default=1000000)),
                ('s3_bucket', models.CharField(default='central', max_length=255)),
                ('s3_bucket_key', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('Do', 'Downloaded'), ('Up', 'Uploaded'), ('De', 'Deleted'), ('Sh', 'Shared'), ('Em', 'Emailed')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('saved_as', models.CharField(max_length=255)),
                ('size', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=500, null=True)),
                ('s3_bucket', models.CharField(default='central', max_length=255)),
                ('s3_bucket_key', models.CharField(max_length=255, unique=True)),
                ('encrypted', models.BooleanField(default=True)),
                ('email_link_available', models.BooleanField(default=True)),
                ('available', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('emailed_to', models.ManyToManyField(related_name='email_recs', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_owner', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(related_name='shared_with_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SharedEncryptionKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrypted_bucket_encryption_key', models.TextField(max_length=4096)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Bucket')),
                ('key_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='activitylog',
            name='bucket',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='server.Bucket'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
