# Generated by Django 2.0 on 2018-06-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='email_link_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='s3_bucket',
            field=models.CharField(default='bashlist-78', max_length=255),
        ),
    ]
