# Generated by Django 2.0 on 2018-06-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20180623_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='s3_bucket_key',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
