# Generated by Django 2.0 on 2018-06-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20180617_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pub_key',
        ),
        migrations.AddField(
            model_name='user',
            name='encrypted_priv_key',
            field=models.TextField(max_length=2048, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='encrypted_pub_key',
            field=models.TextField(max_length=2048, null=True, unique=True),
        ),
    ]
