# Generated by Django 2.0 on 2018-06-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20180627_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='hash_compressed_bytes_latest',
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
