# Generated by Django 2.0 on 2018-07-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_remove_bucket_hash_compressed_bytes_latest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='s3_bucket_key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
