# Generated by Django 2.0 on 2018-06-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20180617_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualencryptionkey',
            name='owner',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='size_used',
            new_name='real_size_used',
        ),
        migrations.RemoveField(
            model_name='bucket',
            name='encrypted_with',
        ),
        migrations.RemoveField(
            model_name='user',
            name='encrypted_pub_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='size_limit',
        ),
        migrations.AddField(
            model_name='user',
            name='encrypted_file_encryption_key',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pub_key',
            field=models.TextField(max_length=4096, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='virtual_size_limit',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AddField(
            model_name='user',
            name='virtual_size_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='encrypted_priv_key',
            field=models.TextField(max_length=4096, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='IndividualEncryptionKey',
        ),
    ]
