# Generated by Django 2.0 on 2018-06-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20180618_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_key',
            field=models.TextField(max_length=4096, unique=True),
        ),
    ]
